### ISSUE TITLE
tip dates <year

### ISSUE THREAD

**Issue by SumeetTiwari07** [Taming-the-BEAST/Basic-tip-dating#1]
Hi,
I am trying to run the beast2 and i was confused about incorporating the tip date information in some cases in my dateset.
If the sampling date is <1990 then how this would be given as input as tip date.
My dataset consist of some fixed dates , some lies under uniform distribution, some from mid 1970s and some are <1990 or even <1983.
I wanted to know how to set tip date <1990 or <1983 in the analysis.

Thanking you,
Sumeet

**Comment by laduplessis** [comment]
Hi Sumeet, 

1. You **always** have to specify an initial value for the tip date. 
2. If the tip date is not known exactly you need to specify a prior distribution, as shown in this tutorial.

E.g. 
- If you know the tip date should be between 1970 and 1980 you can specify an initial date of 1975 and a uniform prior between 1970 and 1980. 
- If you only know that the tip date is <1990 you can guess the initial date to be 1989 and set a uniform prior between 1900 and 1990. Of course the prior you set should be informed with what you already know about the system. If the TMRCA is around 1950 there is no point setting a prior that goes back further than 1950, because the probability of the tip date < 1950 is 0. Similarly, if it is very likely that the true tip date is close to 1990 a uniform prior over a large range would be inappropriate and you would probably get much better mixing setting a shifted lognormal or exponential prior. 

Best wishes,
Louis
